### ISSUE TITLE
Log4j2 compatibility?

### ISSUE THREAD

**Issue by rhomeister** [airbrake/airbrake-java#32]
I would like to use airbrake-java in a project in which we are using Log4j2. However, it seems that airbrake-java is currently not compatible with the new version of Log4j. Is this correct? If so, is anyone working on this?

**Comment by seanguo** [comment]
I have the same question.

**Comment by miere** [comment]
I'm using this library for one week, and maybe I've missed something. But, as far as I've understood the README file, airbrake-java is a simple client to Airbrake. It is using Log4J to provide an out-of-box appender (```airbrake.AirbrakeAppender```) which will make easy to developers send notifications to [airbrake.io](http://airbrake.io).

The Log4J2 Migration guite states that its internal APIs [have changed a little](https://logging.apache.org/log4j/2.x/manual/migration.html). But, I do think is possible to create an Log4J2 appender or a plugin and call the Airbrake API [directly](https://github.com/airbrake/airbrake-java#directly), to achieve the same goal.

**Comment by GregoryHlavac** [comment]
Is there any sort of movement on this planned?

**Comment by davidoram** [comment]
Any progress on this?

**Comment by pkmishra** [comment]
Here you go. https://github.com/pkmishra/airbrake-log4j2 Pull requests are welcome.

**Comment by alexmreis** [comment]
I've emailed Airbrake regarding maintenance of this client, they don't reply to PRs or issues since 2015. Support person at Airbrake told me they would have one of their devs look into it, but so far nothing has been done:

On Fri, Jul 14, 2017 at 3:27 AM, Stuart from Airbrake <stuart.moore@airbrake.intercom-mail.com> wrote:
Hi Alex,

I'm asking our devs to take a look at this. Hopefully someone can approve it soon.

--
Stuart	Stuart from Airbrake       
On Mon, Jul 10, 2017 at 12:57 AM, "Alex Reis" <alex@alexmreis.com> wrote: 
Hi Airbrake,

I'm writing since it seems no one in your company is following up on issues and pull requests on the https://github.com/airbrake/airbrake-java GitHub repository.

I have made a pull request, https://github.com/airbrake/airbrake-java/pull/52, that fixes a pretty nasty bug in the client concerning escaping of quotes a week ago (any java exception that is a re-thrown suffers from that bug) and haven't had any word from the maintainers - in fact, given there are 19 issues and 3 pull requests open, I'm led to believe there IS no maintainer at all for this package.

Seeing as you're a commercial product, I'd expect better support to people actually trying to use it and improve your client libraries - even if it's for talking to Errbit rather than Airbrake.

If you don't intend on maintaining the repository at https://github.com/airbrake/airbrake-java could you please give me commit rights at least, so I can maintain it out of good will to the open source community?

Thank you very much,

Alex Reis

@alexmreis on GitHub

**Comment by vmihailenco** [comment]
We have written new [Java notifier](https://github.com/airbrake/javabrake) and [log4j2 integration](https://github.com/airbrake/log4javabrake2). Please check it out.
